# Generated by Django 2.0.5 on 2018-05-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.TextField()),
                ('course_course_name', models.TextField()),
                ('quarters_offered', models.TextField()),
                ('prereqs', models.TextField()),
                ('course_description', models.TextField()),
                ('offered_online', models.CharField(max_length=1)),
            ],
        ),
    ]
