# Generated by Django 2.0.5 on 2018-05-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursesDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_course_name',
            new_name='course_json',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='offered_online',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='prereqs',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='quarters_offered',
        ),
    ]
