# Generated by Django 2.0.5 on 2018-05-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mycustomuser_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mycustomuser',
            name='faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mycustomuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
