# Generated by Django 2.0.5 on 2018-05-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180528_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycustomuser',
            old_name='faculty',
            new_name='staff',
        ),
    ]
