# Generated by Django 2.0.4 on 2018-06-05 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180605_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
