# Generated by Django 2.0.4 on 2018-06-05 15:59

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180605_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, default=uuid.uuid4, unique=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
