# Generated by Django 2.0.4 on 2018-05-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursec', models.TextField()),
                ('coursesubject', models.TextField()),
                ('coursenumber', models.IntegerField()),
            ],
        ),
    ]
