# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course_search.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
