# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0002_auto_20180411_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_search.Course'),
        ),
    ]
