# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0003_auto_20180411_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='prerequisite',
            new_name='one_prerequisite',
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course_search.CourseRequirements'),
        ),
    ]
