# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0004_auto_20180411_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites_table',
        ),
        migrations.DeleteModel(
            name='CourseRequirements',
        ),
    ]
