# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0005_auto_20180411_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='publications',
            field=models.ManyToManyField(related_name='_course_publications_+', to='course_search.Course'),
        ),
    ]
