# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0006_course_publications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='publications',
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(related_name='_course_prerequisites_+', to='course_search.Course'),
        ),
    ]
