# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0008_remove_course_one_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, null=True, related_name='_course_prerequisites_+', to='course_search.Course'),
        ),
    ]
