# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0011_courserequirements_coursewithnorequirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
    ]
