# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0012_remove_course_prerequisites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserequirements',
            options={'verbose_name': 'Course Requirement', 'verbose_name_plural': 'Course Requirements'},
        ),
        migrations.AlterModelOptions(
            name='coursewithnorequirements',
            options={'verbose_name': 'Course With No Requirement', 'verbose_name_plural': 'Course With No Requirements'},
        ),
    ]
