# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0016_auto_20180412_0028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseWithNoRequirements',
            new_name='Course',
        ),
        migrations.DeleteModel(
            name='AdvancedCourse',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
    ]
