# Generated by Django 2.0.4 on 2018-04-12 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0017_auto_20180412_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course_search.Course'),
        ),
    ]
