# Generated by Django 2.0.4 on 2018-05-15 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_search', '0018_auto_20180412_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='parent',
        ),
    ]
